#!/bin/bash

# script to launch AIRSS searches using repose at a range of pressures
min_press=$1
max_press=$2
press_step=$3
max_samples=$4
mpinp=$5

# determine fileroot
filename=`ls *.eddp`
fileroot=${filename%.*}

# calculate number of simultaneous jobs such that the node is filled up
num_threads=`lscpu | awk '/^CPU\(s\)/ {print $2}'`
threads_per_core=`lscpu | awk '/Thread/ {print $4}'`
num_cores=$(awk "BEGIN {print $num_threads/$threads_per_core; exit}")
num_simultaneous_jobs=$(awk "BEGIN {print $num_cores/$mpinp; exit}")

for i in `seq $min_press $press_step $max_press`; do
	
	mkdir ${i}_GPa
	cp ${fileroot}.{cell,par} ${i}_GPa
	awk '{print "../" $0}' ${fileroot}.eddp > ${i}_GPa/${fileroot}.eddp
	cd ${i}_GPa
	
	for j in `seq 1 $num_simultaneous_jobs`; do
		airss.pl -pressure $i -devmax 5 -repose -mpinp $mpinp -max $max_samples -pack -workdir /dev/shm -seed ${fileroot} &
	done
	
	wait

	cd ..

done
