#!/bin/bash

# script that uses the EDDP wobble phonon code to estimate the Gibbs free energy as a function of temperature in the quasiharmonic approximation
# it does this on the basis of an existing enthalpy calculation done the AIRSS style, and must be run in a good_castep directory

while getopts ":t:s:n:r:m:h" opt; do
        case $opt in
                t)
			# maximum temperature at which we evaluate the vibrational energy
                        max_temp=$OPTARG;;
                s)
			# step between temperatures
                        t_step=$OPTARG;;
                n)
			# number of atoms for the supercell
			natoms_supercell=$OPTARG;;
		r)
			# the structure against which to reference the final plots
			reference_structure=$OPTARG;;
		m)
			# the number of OpenMP threads
			mpinp=$OPTARG;;
                h)
                        echo "Script to calculate the free energy of structures at different temperatures"
                        echo "Usage: calculate_free_energy_wobble [-t max_temp] [-s t_step] [-n natoms_supercell]"
                        echo ""
                        echo "Optional arguments"
                        echo "-t max_temp [K]        : the highest temperature at which the vibrational energy is evaluated"
                        echo "-s t_step [K]          : the increment between successive temperatures at which the vibrational energy is evaluated "
                        echo "-n natoms_supercell    : the number of atoms in the supercell used for the phonon calculation"
                        echo "-r reference_structure : the structure against which to reference the final plots - the following part of a res file name: seed-reference_structure.res"
			echo "-m mpinp               : the number of OpenMP threads used for the wobble calculation. Note that using less threads does not mean more jobs will be started - this is a command line option in case only part of the node is desired."
                        echo "-h                     : print this message and exit"
                        echo ""
                        echo "If no variables are supplied, the following defaults are used: -t 500 -s 25 -n 1000 -m $(nproc --all). The reference structure is whichever is alphabetically first."
                        exit 1
        esac
done

if [ -z $max_temp ]; then
	max_temp=500
fi

if [ -z $t_step ]; then
	t_step=25
fi

if [ -z $natoms_supercell ]; then
	natoms_supercell=1000
fi

if [ -z $mpinp ]; then
	mpinp=$(nproc --all)
fi

if [ -z $reference_structure ]; then
	first_structure=`ls *.res | head -1`
	reference_structure=${first_structure#*-}
	reference_structure=${reference_structure%.*}
fi

# translate [max_temp, step] into the wobble-used [max_temp,ntemp]
ntemp=$(awk "BEGIN {print 1+$max_temp/$t_step; exit}")

# iterate over every single res file present in the directory
for i in *.res; do
	seed=${i%.*}
	form_press_name=`echo $i | awk 'BEGIN {FS="-"} {print $1}'`
	
	# copy the relevant .eddp to match the complete fileroot of the .res file
	cp ${form_press_name}.eddp ${seed}.eddp
	
	cabal res cell < ${seed}.res > ${seed}.cell

	# run wobble - stdout contains nothing but the energies [eV] as a function of temperature
	wobble -therm -mpinp $mpinp -natom $natoms_supercell -unit meV -tmax $max_temp -ntemp $ntemp $seed 1> ${seed}_temperature_energy.dat 2> wobble.log
	
	# wobble seems to create this even when -dos is not specified in the command - here, we delete it
	rm -f ${seed}-dos.agr
	
	while read line; do

		temp=`echo $line | awk '{print $1}'`
		energy=`echo $line | awk '{print $2}'`

		if [ ! -d temp_${temp}_K ]; then
			mkdir temp_${temp}_K
		fi
		
		if [ $energy != "-Infinity" ]; then
		
			# the energy in wobble becomes infinite when there are (a large number of?) soft modes - we neglect them here as they break the fit
			# add the vibrational energy to the enthalpy
			awk -v CONVFMT=%.14g -v awk_energy=$energy '/TITL/ {gsub(/\-[0-9]+\.\S*/, $5+awk_energy)} 1' $i > temp_${temp}_K/${i}

		fi

	done < ${seed}_temperature_energy.dat
	
	rm ${seed}.eddp	

done

# the pressure must now be rescaled to account for the phonon contribution to this quantity

for i in temp_*_K; do
	cd $i

	cp ~/bin/python_scripts/Caesar/calculate_phonon_pressure.py .

	python3 calculate_phonon_pressure.py $reference_structure
	
	gnuplot phonon_pressure_energy.gnu

	cd ..
done

# plot phase diagram

cp ~/bin/python_scripts/pressure_temperature_phase_diagram.py .
python3 pressure_temperature_phase_diagram.py
