#!/bin/bash

# run in directory containing input files for a CASTEP run

first_energy=$1
final_energy=$2
energy_step=$3

# auto-determine fileroot
name=`ls *.param`
fileroot=`python -c "print '$name'.split('.')[0]"`

ncores=`nproc --all`

if [ ! -f cut_off_energy.txt ]; then
	echo "Cutoff Energy [eV]; Total calculated energy [eV]; Time [s]" >> cut_off_energy.txt
fi

for cutoff in `seq $first_energy $energy_step $final_energy`; do
	
	mkdir cut_off_energy_${cutoff}	
	cp ${fileroot}.* cut_off_energy_${cutoff}
	cp *.usp* cut_off_energy_${cutoff}
	cp *pot* cut_off_energy_${cutoff}
	
	cd cut_off_energy_${cutoff}
	
	sed -i "s/XYZ/${cutoff}/g" ${fileroot}.param

	mpirun -n $ncores castep.mpi $fileroot
	
	# the output format for the energy is different between SOC and not SOC calculations, so here we determine which it is
	is_soc=`awk '/spin-orbit coupling/ {print $4}' ${fileroot}.castep`

	if [ $is_soc == "off" ]; then
		# calculation is not spin-orbit coupled
		energy=`awk '/Final energy/ {print $5}' ${fileroot}.castep`
	else
		energy=`awk '/Final energy/ {print $4}' ${fileroot}.castep`
	fi	

	time=`awk '/Total time/ {print $4}' ${fileroot}.castep`
        echo $cutoff $energy $time >> ../cut_off_energy.txt
	
	rm ${fileroot}.check ${fileroot}.bands ${fileroot}.castep_bin

	cd ..
done
