#!/bin/bash

# run in directory containing input files for a CASTEP run
# go from least dense (first_spacing) to most dense (final_spacing) grid in increments of spacing_reduction

first_spacing=$1
final_spacing=$2
spacing_reduction=$3

ncores=`nproc --all`

# auto-determine fileroot
name=`ls *.param`
fileroot=`python -c "print '$name'.split('.')[0]"`

if [ ! -f kpoints_mp_spacing.txt ]; then
        echo "K-point grid density [1/Ang]; Total calculated energy per atom [eV]; Time [s]" >> kpoints_mp_spacing.txt
fi

while [ `python -c "print int($first_spacing >= $final_spacing)"` -eq 1 ]; do

	mkdir spacing_${first_spacing}	
	cp ${fileroot}.* spacing_${first_spacing}
	cp *.usp* spacing_${first_spacing}
	cp *pot* spacing_${first_spacing}
	
	cd spacing_${first_spacing}
	
	sed -i "s/AA/${first_spacing}/g" ${fileroot}.cell

	mpirun -n $ncores castep.mpi $fileroot

	# the output format for the energy is different between SOC and not SOC calculations, so here we determine which it is
	is_soc=`awk '/spin-orbit coupling/ {print $4}' ${fileroot}.castep`

        if [ $is_soc == "off" ]; then
                # calculation is not spin-orbit coupled
                energy=`awk '/Final energy/ {print $5}' ${fileroot}.castep`
        else
                energy=`awk '/Final energy/ {print $4}' ${fileroot}.castep`
        fi
	
	time=`awk '/Total time/ {print $4}' ${fileroot}.castep`

	natoms=`grep "Total number of ions in cell" ${fileroot}.castep | awk 'BEGIN {FS="="}; {print $2}'`
        energy_per_atom=`python -c "print(float('$energy')/float('$natoms'))"`

        echo $first_spacing $energy_per_atom $time >> ../kpoints_mp_spacing.txt

	rm ${fileroot}.check ${fileroot}.bands ${fileroot}.castep_bin
	
	first_spacing=`echo $first_spacing - $spacing_reduction | bc`

	cd ..
done
