#!/bin/bash

# run in directory containing input files for a CASTEP run

first_energy=$1
final_energy=$2
energy_step=$3

# auto-determine fileroot
name=`ls *.param`
fileroot=`python3 -c "print('$name'.split('.')[0])"`

ncores=$((`nproc --all`/2))

if [ ! -f cut_off_energy.txt ]; then
	echo "Cutoff Energy [eV]; Total calculated energy per atom [eV]; Time [s]" >> cut_off_energy.txt
fi

for cutoff in `seq $first_energy $energy_step $final_energy`; do
	
	mkdir cut_off_energy_${cutoff}	
	cp ${fileroot}.* cut_off_energy_${cutoff}
	cp *.usp* cut_off_energy_${cutoff}
	cp *pot* cut_off_energy_${cutoff}
	
	cd cut_off_energy_${cutoff}
	
	sed -i "s/XYZ/${cutoff}/gi" ${fileroot}.param

	mpirun -n $ncores castep.mpi $fileroot
	
	# the output format for the energy is different between SOC and not SOC calculations, so here we determine which it is
	is_soc=`awk '/spin-orbit coupling/ {print $4}' ${fileroot}.castep`

	# the same goes for non-metallic (fix_occupancy=true) and metallic calculations
	is_non_metallic=`awk '/non-metallic/ {print}' ${fileroot}.castep`
	# this will be empty if the calculations is metallic

	if [ $is_soc == "off" ] && [ `python3 -c "print(int(not '$is_non_metallic'))"` -eq 1 ]; then
		# calculation is metallic and not spin-orbit coupled
		energy=`awk '/Final energy/ {print $5}' ${fileroot}.castep`
	else
		energy=`awk '/Final energy/ {print $4}' ${fileroot}.castep`
	fi	

	time=`awk '/Total time/ {print $4}' ${fileroot}.castep`

	# determine number of atoms per UC in order to calculate the total energy per atom

	natoms=`grep "Total number of ions in cell" ${fileroot}.castep | awk 'BEGIN {FS="="}; {print $2}'`
	energy_per_atom=`python3 -c "print(float('$energy')/float('$natoms'))"`

	echo $cutoff $energy_per_atom $time >> ../cut_off_energy.txt
	
	rm ${fileroot}.check ${fileroot}.bands ${fileroot}.castep_bin

	cd ..
done
