#!/bin/bash

min_press=$1
max_press=$2
press_step=$3
eddp_calc=$4
struc_name=$5 # eg for Po_${press}p0-HCP.res, we need Po-HCP

# determine structure name parts
seed=${struc_name%%-*}
struc_name_rest=${struc_name#*-}

# in principle, it should be possible to supply an eddp_calc which does not contain good_castep in the top-level directory. This does cause problems with the output filename, so we choose only the name of the top-level directory

if [ ! -f ${struc_name}_dft_${eddp_calc}_enthalpies.dat ]; then
	echo "Pressure [GPa]; DFT enthalpy [eV/atom]; EDDP enthalpy [eV/atom]; DFT enthalpy - EDDP enthalpy [eV/atom]" > ${struc_name}_dft_${eddp_calc%%/*}_enthalpies.dat
fi

for press in `seq $min_press $press_step $max_press`; do

	# calculate DFT energy per atom
	dft_energy=`awk '/TITL/ { printf ("%f", $5 ); }' DFT/good_castep/${seed}_${press}p0-${struc_name_rest}.res`
	dft_sfac_line=`awk '/SFAC/{print NR}' DFT/good_castep/${seed}_${press}p0-${struc_name_rest}.res`
	dft_end_line=`awk '/END/{print NR}' DFT/good_castep/${seed}_${press}p0-${struc_name_rest}.res`
	dft_natoms=$((dft_end_line - dft_sfac_line - 1))
	dft_energy_per_atom=`awk -v awk_energy=$dft_energy -v awk_natoms=$dft_natoms 'BEGIN {printf ("%f", awk_energy/awk_natoms); exit}'`

	# calculate EDDP energy per atom
	eddp_energy=`awk '/TITL/ { printf ("%f", $5 ); }' ${eddp_calc}/good_castep/${seed}_${press}p0-${struc_name_rest}.res`
	eddp_sfac_line=`awk '/SFAC/{print NR}' ${eddp_calc}/good_castep/${seed}_${press}p0-${struc_name_rest}.res`
	eddp_end_line=`awk '/END/{print NR}' ${eddp_calc}/good_castep/${seed}_${press}p0-${struc_name_rest}.res`
	eddp_natoms=$((eddp_end_line - eddp_sfac_line - 1))
	eddp_energy_per_atom=`awk -v awk_energy=$eddp_energy -v awk_natoms=$eddp_natoms 'BEGIN {printf ("%f", awk_energy/awk_natoms); exit}'`

	energy_difference=`awk "BEGIN {print $dft_energy_per_atom - $eddp_energy_per_atom; exit}"`
	echo $press $dft_energy_per_atom $eddp_energy_per_atom $energy_difference >> ${struc_name}_dft_${eddp_calc%%/*}_enthalpies.dat
done
