#!/bin/bash

dft_path=$1 # path to the DFT results

# iterate over all .res files - the same ones must be present in the DFT directory
for i in *.res; do
	
	# read relevant quantities
	natoms=`awk 'NR==1{print $8}' $i`
	energy_eddp=`awk 'NR==1{print $5}' $i`
	energy_dft=`awk 'NR==1{print $5}' ${dft_path}/${i}`
	dev=`res2dev ${i%.*} | awk '{print $2}'`

	symm_group=`awk 'NR==1{print $9}' $i | sed "s%\/%%g"`
	symm_group=`echo ${symm_group#(*}`
	symm_group=`echo ${symm_group%)*}`
	
	# calculate the error compared to DFT and convert to meV/atom
	energy_difference=$(awk "BEGIN {print sqrt(($energy_eddp-($energy_dft))^2)*1000/$natoms; exit}")
	dev_per_atom=$(awk "BEGIN {print $dev*1000/$natoms; exit}")

	if [ ! -f dft_error_deviation_comparison_${symm_group}.txt ]; then
		echo "# Structure; | Error compared to DFT | [meV/atom]; Deviation [meV/atom]" > dft_error_deviation_comparison_${symm_group}.txt
	fi

	echo ${i%.*} $energy_difference $dev_per_atom >> dft_error_deviation_comparison_${symm_group}.txt

done

# generate gnuplot script

echo "set terminal postscript eps colour font 'Helvetica,20'" > dft_error_deviation_comparison.gnu
echo "set style data points" >> dft_error_deviation_comparison.gnu
echo "set key top left" >> dft_error_deviation_comparison.gnu
echo "set key box lt -1 lw 2 width 2 height 1.5 opaque font 'Helvetica,20'" >> dft_error_deviation_comparison.gnu
echo "set output '| epstopdf --filter --outfile=dft_error_deviation_comparison.pdf'" >> dft_error_deviation_comparison.gnu
echo "set xlabel '| Error compared to DFT | [meV/atom]'" >> dft_error_deviation_comparison.gnu
echo "set ylabel 'Deviation [meV/atom]'" >> dft_error_deviation_comparison.gnu

echo "set linetype 1 lc rgb '#DC143C'" >> dft_error_deviation_comparison.gnu
echo "set linetype 2 lc rgb '#FFCC00'" >> dft_error_deviation_comparison.gnu
echo "set linetype 3 lc rgb '#66A61E'" >> dft_error_deviation_comparison.gnu
echo "set linetype 4 lc rgb '#191970'" >> dft_error_deviation_comparison.gnu
echo "set linetype 5 lc rgb '#7570B3'" >> dft_error_deviation_comparison.gnu
echo "set linetype 6 lc rgb '#E7298A'" >> dft_error_deviation_comparison.gnu
echo "set linetype 7 lc rgb '#1E90FF'" >> dft_error_deviation_comparison.gnu
echo "set linetype 8 lc rgb '#1B9E77'" >> dft_error_deviation_comparison.gnu
echo "set linetype 9 lc rgb '#B8860B'" >> dft_error_deviation_comparison.gnu
echo "set linetype cycle 9" >> dft_error_deviation_comparison.gnu

plot="plot"

for i in dft_error_deviation_comparison_*.txt; do
	title=`echo ${i#*_*_*_*_}`
	title=`echo ${title%.*}`
	plot+=" '$i' u 2:3 w points pt 7 ps 1.5 title '${title}',"
done

plot=${plot::-1} 2> /dev/null

echo $plot >> dft_error_deviation_comparison.gnu
gnuplot dft_error_deviation_comparison.gnu
