#!/bin/bash

min_press=$1
max_press=$2
press_step=$3
eddp_calc=$4
struc_name=$5 # eg for Po_${press}p0-HCP.res, we need Po-HCP

# determine structure name parts
seed=${struc_name%%_*}
struc_name_rest=${struc_name#*-}

if [ ! -f ${struc_name}_dft_${eddp_calc}_enthalpies.dat ]; then
	echo "Pressure [GPa]; DFT energy [eV]; EDDP energy [eV]" > ${struc_name}_dft_${eddp_calc}_enthalpies.dat
fi

for press in `seq $min_press $max_press $press_step`; do
	dft_energy=`awk '/TITL/ {print $5}' DFT/good_castep/${seed}_${press}p0-${struc_name_res}.res`
	eddp_energy=`awk '/TITL/ {print $5}' ${eddp_calc}/good_castep/${seed}_${press}p0-${struc_name_res}.res`
	echo $press $dft_energy $eddp_energy >> ${struc_name}_dft_${eddp_calc}_enthalpies.dat
done
