#!/bin/bash

# script to calculate the energy difference between two structures, where one component of a single atom's position is placed at two different user-supplied positions
# works in all coordinate systems; the user must ensure the difference is sensible in the chosen system

# run in directory containing input file ${fileroot}.inp for a CP2k run

first_energy=$1
final_energy=$2
energy_step=$3
first_x=$4
second_x=$5

ncores=$((`nproc --all`/2))

ha_to_ev=27.211396132

# determine the displaced x-component

# auto-determine fileroot
name=`ls *.inp`
fileroot=`python3 -c "print('$name'.split('.')[0])"`

if [ ! -f cutoff.txt ]; then
	echo "Cutoff Energy [Ry]; Total calculated energy difference per atom [eV]; Time for calculation at $first_x [s]; Time for calculation at $second_x [s]" >> cutoff.txt
fi

for cutoff in `seq $first_energy $energy_step $final_energy`; do
	
	mkdir cutoff_${cutoff}	
	cp *BASIS* cutoff_${cutoff}
	cp *POTENTIAL* cutoff_${cutoff}
	
	sed "s/XYZ/${cutoff}/gi" ${fileroot}.inp > cutoff_${cutoff}/${fileroot}.inp
	
	cd cutoff_${cutoff}

	mkdir first_structure
	cp *BASIS* first_structure
	cp *POTENTIAL* first_structure

	sed "s/AAA/${first_x}/gi" ${fileroot}.inp > first_structure/${fileroot}.inp
	
	cd first_structure

	mpirun -np $ncores cp2k.popt -o ${fileroot}.out ${fileroot}.inp
	
	first_energy=`grep "ENERGY" ${fileroot}.out | tail -1 | awk '{print $9}'`
	first_time=`grep "CP2K" ${fileroot}.out | tail -1 | awk '{print $6}'`

	# determine number of atoms per UC in order to calculate the total energy per atom

	natoms=`awk '/- Atoms/ {print $3}' ${fileroot}.out`
	
	rm -r ${fileroot}-RESTART.wfn*

	cd ..

	mkdir second_structure
	cp *BASIS* second_structure
	cp *POTENTIAL* second_structure

	sed "s/AAA/${second_x}/gi" ${fileroot}.inp > second_structure/${fileroot}.inp
	
	cd second_structure

	mpirun -np $ncores cp2k.popt -o ${fileroot}.out ${fileroot}.inp
	
	second_energy=`grep "ENERGY" ${fileroot}.out | tail -1 | awk '{print $9}'`
	second_time=`grep "CP2K" ${fileroot}.out | tail -1 | awk '{print $6}'`
	
	rm -r ${fileroot}-RESTART.wfn*

	cd ..
	
	energy_difference=`python3 -c "print(float('$second_energy')*float('$ha_to_ev')-(float('$first_energy')*float('$ha_to_ev')))"`

	energy_difference_per_atom=`python3 -c "print(float('$energy_difference')/float('$natoms'))"`

	echo $cutoff $energy_difference_per_atom $first_time $second_time >> ../cutoff.txt

	cd ..
done
