#!/bin/bash

# run in directory containing input file ${fileroot}.inp for a CP2k run

first_energy=$1
final_energy=$2
energy_step=$3

# auto-determine fileroot
name=`ls *.inp`
fileroot=`python3 -c "print('$name'.split('.')[0])"`

ha_to_ev=27.211396132

if [ ! -f cutoff.txt ]; then
	echo "Cutoff Energy [Ry]; Total calculated energy per atom [eV]; Time" >> cutoff.txt
fi

for cutoff in `seq $first_energy $energy_step $final_energy`; do
	
	mkdir cutoff_${cutoff}	
	cp *BASIS* cutoff_${cutoff}
	cp *POTENTIAL* cutoff_${cutoff}
	
	sed "s/XYZ/${cutoff}/gi" ${fileroot}.inp > cutoff_${cutoff}/${fileroot}.inp
	
	cd cutoff_${cutoff}

	mpirun -np $NCORES cp2k.popt -o ${fileroot}.out ${fileroot}.inp
	
	energy=`grep "ENERGY" ${fileroot}.out | tail -1 | awk '{print $9}'`

	time=`grep "CP2K" ${fileroot}.out | tail -1 | awk '{print $6}'`

	# determine number of atoms per UC in order to calculate the total energy per atom

	natoms=`awk '/- Atoms/ {print $3}' ${fileroot}.out`
	energy_per_atom=`python3 -c "print(float('$energy')*float('$ha_to_ev')/float('$natoms'))"`

	echo $cutoff $energy_per_atom $time >> ../cutoff.txt
	
	rm -r ${fileroot}-RESTART.wfn*

	cd ..
done
