#!/bin/bash

# determine prefix

prefix_raw=`awk '{IGNORECASE=1}; {FS="="}; /preFix/ {print $2}' pw.in`
prefix=${prefix_raw%,*}
prefix=${prefix%"'"}
prefix=${prefix%'"'}
prefix=${prefix#"'"}
prefix=${prefix#'"'}

rm -r ${prefix}.* nohup.out
