#!/bin/bash

# determine file root
name=`ls *.param`

fileroot=`python3 -c "print('$name'.split('.')[0])"`

for file in *; do

	if [ $file != ${fileroot}.cell ] && [ $file != ${fileroot}.param ] &&  [ `python3 -c "print(int(('$file'.endswith('usp') or '$file'.endswith('uspso') or '$file'.endswith('uspcc') or ('pot' in '$file')) and not ('OTF' in '$file')))"` -eq 0 ]; then
		rm $file
	fi
done
