#!/bin/bash

chgcar_del=`grep "ICHARG" INCAR`

if [ `python3 -c "print(int(('$chgcar_del'.split('=')[1].startswith('1 ')) or ('$chgcar_del'.split('=')[1].startswith('1!')) or ('$chgcar_del'.split('=')[1].startswith('1#')) or ('$chgcar_del'.split('=')[1].startswith('11'))))"` -eq 0 ]; then
	# don't delete CHGCAR if were trying to read the charge density from it - indicated by ICHARG=1, 11
	rm CHGCAR
fi

wavecar_del=`grep "ISTART" INCAR`

if [ `python3 -c "print(int('$wavecar_del'.split('=')[1].startswith('0')))"` -eq 1 ]; then
       rm WAVECAR
fi

rm CHG
rm CONTCAR
rm DOSCAR
rm EIGENVAL
rm OSZICAR
rm PCDAT
rm REPORT
rm vasprun.xml
rm XDATCAR
rm IBZKPT
rm OUTCAR
rm PROCAR
rm nohup.out
