#!/bin/bash

# script to convert an enthalpy plot generated using ca -e to pdf

# detect fileroot

for file in *.agr; do
	fileroot=`echo ${file%.*}`

	xmgrace -hardcopy ${fileroot}.agr -hdevice EPS -printfile ${fileroot}.eps
	epstopdf ${fileroot}.eps ${fileroot}.pdf

	rm ${fileroot}.eps
done
