#!/bin/bash

# script to convert an enthalpy plot generated using ca -e to pdf

# detect fileroot

file=`ls *.agr`
fileroot=`echo ${file%.*}`

grace -hardcopy ${fileroot}.agr -hdevice EPS -printfile ${fileroot}.eps
epstopdf ${fileroot}.eps ${fileroot}.pdf

rm ${fileroot}.eps
