#!/bin/bash

# script to extract the free energies of a set of wobble phonon calculations at a set of pressures over a range temperatures and store them in .txt file

while getopts ":n:m:s:t:l:i:p:h" opt; do
        case $opt in
                n)
			# the name of the file containing the vibrational energy without the pressure component - eg if we want the vibrational energies from Po_<press>p0-Pm-3m.dat, this must be Po-Pm-3m.dat
                        filename=$OPTARG;;
		m)
			# the minimum temperature
			t_min=$OPTARG;;
                s)
			# step between temperatures
                        t_step=$OPTARG;;
                t)
			# the maximum temperature
			t_max=$OPTARG;;
		l)
			# the lowest pressure
			p_min=$OPTARG;;
		i)      
			# the pressure increment
			p_step=$OPTARG;;
		p)
			# the highest pressure
			p_max=$OPTARG;;
                h)
                        echo "Script to extract the vibrational energy as a function of temperature calculated by wobble at a set of pressures"
                        echo "Usage: extract_wobble_vibrational_energies -n filename [-m t_min] [-s t_step] [-t t_max] [-l p_min] [-i p_step] [-p p_max]"
                        echo ""
			echo "Required arguments"
			echo "-n filename            : the actual filenames will be of the form, eg Po_<press>p0-Pm-3m.dat. The pressure component is added to the name by this script, hence this argument must be Po-Pm-3m.dat (for instance)"
			echo ""
                        echo "Optional arguments"
			echo "-m t_min [K]           : the minimum temperature at which the vibrational energy is extracted"
                        echo "-s t_step [K]          : the step between successive temperatures at which the vibrational energy is extracted"
                        echo "-t t_max [K]           : the maximum temperature at which the vibrational energy is extracted"
                        echo "-l p_min [GPa]         : the lowest pressure at which the vibrational energy is extracted"
			echo "-i p_step [GPa]        : the increment between successive pressures at which the vibrational energy is extracted"
			echo "-p p_max [GPa]         : the highest pressure at which the vibrational energy is extracted"
			echo "-h                     : print this message and exit"
                        echo ""
                        echo "A filename MUST be supplied. For the temperatures and pressures, the following defaults apply: -m 0 -s 500 -t 2000 -l 0 -i 5 -p 100."
                        exit 1
        esac
done

if [ -z $filename ]; then
	echo "You have not supplied a filename, which MUST be given."
	exit 1
fi

# split up filename
fileroot=${filename%.*}
fileseed=${filename%%-*}
filename_rest=${filename#*-}

if [ -z $t_min ]; then
        t_min=0
fi

if [ -z $t_step ]; then
	t_step=500
fi

if [ -z $t_max ]; then
	t_max=2000
fi

if [ -z $p_min ]; then
	p_min=0
fi

if [ -z $p_step ]; then
	p_step=5
fi

if [ -z $p_max ]; then
	p_max=100
fi

if [ ! -f vibrational_energies_${fileroot}.dat ]; then 
	echo "#               Energy [eV]" > vibrational_energies_${fileroot}.dat
fi

# set up list of all temperatures for writing to file
temperatures_list="# P [GPa] | T [K]"

for i in `seq $t_min $t_step $t_max`; do
	temperatures_list+=" $i"
done

echo $temperatures_list >> vibrational_energies_${fileroot}.dat

for press in `seq $p_min $p_step $p_max`; do

	# set up energies list for writing to file
	energies_list="$press"

	# set up full file name
	press_filename=${fileseed}_${press}p0-${filename_rest}

	for i in `seq $t_min $t_step $t_max`; do
		energy=`grep "^ *$i\." $press_filename | awk '{print $2}'`
		energies_list+=" $energy"
	done

	echo $energies_list >> vibrational_energies_${fileroot}.dat

done

echo "" >> vibrational_energies_${fileroot}.dat
