#!/bin/bash

# run in directory containing input file pw.in for a QE run

first_energy=$1
final_energy=$2
energy_step=$3

ry_to_ev=13.605698066

if [ ! -f ecutrho.txt ]; then
	echo "Density Cutoff Energy [Ry]; Total calculated energy per atom [eV]; Time" >> ecutrho.txt
fi

for cutoff in `seq $first_energy $energy_step $final_energy`; do
	
	mkdir ecutrho_${cutoff}	
	cp *upf ecutrho_${cutoff}
	cp *UPF ecutrho_${cutoff}
	
	sed "s/XYZ/${cutoff}/gi" pw.in > ecutrho_${cutoff}/pw.in
	
	cd ecutrho_${cutoff}

	mpirun -np $NCORES pw.x -i pw.in > pw.out
	
	energy=`awk '/total energy/ {print $5}' pw.out | tail -2 | head -1`

	time=`awk '/WALL/ {print $5}' pw.out | tail -1`

	# determine number of atoms per UC in order to calculate the total energy per atom

	natoms_raw=`awk '{IGNORECASE=1}; {FS="="}; /nat/ {print $2}' pw.in`
	natoms=`echo ${natoms_raw%,*}`
	energy_per_atom=`python3 -c "print(float('$energy')*float('$ry_to_ev')/float('$natoms'))"`

	echo $cutoff $energy_per_atom $time >> ../ecutrho.txt
	
	rm -r *.save

	cd ..
done
