#!/bin/bash

# wrapper for VASP run, which only exits when the run has been completed successfully

mpi_tasks_per_node=$1
ncores=$2

while [ `python3 -c "print(int(not '$run_successful'))"` -eq 1 ]; do
	# not '$run_successful' is true, that is, the run was not successful ($run_successful is empty)
	# also true at the first step, where $run_successful is unset and we have an empty string

	delete_vasp_output

	if [ `awk '{FS = "="} /LSORBIT/ {print $2}' INCAR` == ".TRUE." ]; then
		mpirun -ppn $mpi_tasks_per_node -np $ncores vasp_ncl > vasp.out
	else
		mpirun -ppn $mpi_tasks_per_node -np $ncores vasp_std > vasp.out
	fi

	run_successful=`grep "General" OUTCAR`
done
