#!/bin/bash

T_min=$1 # the minimum temperature
T_max=$2 # the maximum temperature
T_step=$3 # by how much the temperature is incremented
lower_band=$4 # index of the lower band - for the upper band, $lower_band+1 is assumed
kx=$5
ky=$6
kz=$7
# the k-point components in reciprocal coordinates

# update k-coordinates for consistent writing with Python
kx=`python3 -c "print(str(float("$kx")))"`
ky=`python3 -c "print(str(float("$ky")))"`
kz=`python3 -c "print(str(float("$kz")))"`

higher_band=$((lower_band+1))

echo "What is the static difference between band $lower_band and $higher_band (in eV) at k-point $kx $ky $kz for this system?"
read static_band_difference

echo "#T [K]; Band Difference [eV]; Change compared to static [meV]" > bands_${lower_band}_${higher_band}_k_${kx}_${ky}_${kz}_difference_temperature.dat

for i in `seq $T_min $T_step $T_max`; do
	
	cd T_${i}K

	cp ~/bin/python_scripts/band_kpoint_energy.py .
	python3 band_kpoint_energy.py $lower_band "$kx $ky $kz"
	python3 band_kpoint_energy.py $higher_band "$kx $ky $kz"

	lower_energy=`awk '/Energy/ {print $3}' band_${lower_band}_k_${kx}_${ky}_${kz}_energy.dat`
	higher_energy=`awk '/Energy/ {print $3}' band_${higher_band}_k_${kx}_${ky}_${kz}_energy.dat`
	band_difference=`python3 -c "print(float('$higher_energy')-float('$lower_energy'))"`
	band_difference_change=`python3 -c "print(1000*float('$band_difference')-1000*float('$static_band_difference'))"`

	echo $i $band_difference $band_difference_change >> ../bands_${lower_band}_${higher_band}_k_${kx}_${ky}_${kz}_difference_temperature.dat
	
	cd ..
done

cp ~/bin/python_scripts/thermal_expansion_band_difference.py . 
python3 thermal_expansion_band_difference.py $lower_band "$kx $ky $kz"

gnuplot bands_${lower_band}_${higher_band}_k_${kx}_${ky}_${kz}_difference_temperature.gnu
gnuplot bands_${lower_band}_${higher_band}_k_${kx}_${ky}_${kz}_difference_change_temperature.gnu
