#!/bin/bash

# run in directory containing input files for a VASP run

first_energy=$1
final_energy=$2
energy_step=$3

ncores=`nproc --all`

if [ ! -f energy_ENCUT.txt ]; then
        echo "Cutoff Energy [eV]; Total calculated energy [eV]; Time [s]" > energy_ENCUT.txt
fi

for cutoff in `seq $first_energy $energy_step $final_energy`; do

	mkdir ENCUT_${cutoff}
	
	cp PO*CAR ENCUT_${cutoff}
	cp KPOINTS ENCUT_${cutoff}

	sed "s/XYZ/${cutoff}/g" INCAR > ENCUT_${cutoff}/INCAR

	cd ENCUT_${cutoff}/

	if [ `awk '{FS = "="} /LSORBIT/ {print $2}' INCAR` == ".TRUE." ]; then
		mpirun -np $ncores vasp_ncl
	else
		mpirun -np $ncores vasp_std
	fi

	run_successful=`grep "General" OUTCAR` # when VASP completes a job successfully, it prints some "General timing and accounting informations for this job" at the very end of OUTCAR. Thus, if the job terminates prematurely, run_successful will be empty

	while [ `python -c "print int(not '$run_successful')"` -eq 1 ]; do
		# not '$run_successful' is true, that is, the run was not successful ($run_successful is empty)
		delete_vasp_output

		if [ `awk '{FS = "="} /LSORBIT/ {print $2}' INCAR` == ".TRUE." ]; then
			mpirun -np $ncores vasp_ncl
		else
			mpirun -np $ncores vasp_std
		fi

		run_successful=`grep "General" OUTCAR`
	done
	# when this loop is left, we had a successful run

        # distinguish between Bloechl smearing (-5) and other methods
        if [ `awk '{FS = "="} /ISMEAR/ {print $2}' INCAR` == "-5" ]; then
                # Bloechl smearing - some extra lines are printed (Bloechl correction)
                energy=`grep "energy" OUTCAR | tail -3 | head -1 | awk '{print $NF}'`
        else
                energy=`grep "energy" OUTCAR | tail -1 | awk '{print $NF}'`
        fi

        time=`grep "Elapsed time" OUTCAR | awk 'BEGIN {FS=":"}; {print $2}'`

	cd ..

	echo $cutoff $energy $time >> energy_ENCUT.txt

done
