#!/bin/bash

ncores=`nproc --all`

first_split=$1
last_split=$2

for i in `seq $first_split $last_split`; do
	mkdir split-0$i
	mv KPOINTS_band_split_$i split-0$i/KPOINTS
	cp *CAR split-0$i/

	cd split-0$i

	if [ ! -f "OUTCAR" ]; then
		if [ `awk '{FS = "="} /LSORBIT/ {print $2}' INCAR` == ".TRUE." ]; then
			mpirun -np $ncores vasp_6.1_ncl
		else
			mpirun -np $ncores vasp_6.1_std 
		fi

		run_successful=`grep "General" OUTCAR` # when VASP completes a job successfully, it prints some "General timing and accounting informations for this job" at the very end of OUTCAR. Thus, if the job terminates prematurely, run_successful will be empty

                while [ `python -c "print int(not '$run_successful')"` -eq 1 ]; do
                        # not '$run_successful' is true, that is, the run was not successful ($run_successful is empty)
                        delete_vasp_output

                        if [ `awk '{FS = "="} /LSORBIT/ {print $2}' INCAR` == ".TRUE." ]; then
                                mpirun -np $ncores vasp_6.1_ncl
                        else
                                mpirun -np $ncores vasp_6.1_std
                        fi

                        run_successful=`grep "General" OUTCAR`
                done
                # when this loop is left, we had a successful run
	fi
	cd ..
done
