#!/bin/bash

ncores=$((`nproc --all`/2))

first_split=$1
last_split=$2

for i in `seq $first_split $last_split`; do
	mkdir split-0$i
	mv KPOINTS_band_split_$i split-0$i/KPOINTS
	cp *CAR split-0$i/

	cd split-0$i

	if [ ! -f "OUTCAR" ]; then
		run_vasp_stable
	fi
	cd ..
done
