#!/bin/bash

ncores=$((`nproc --all`/2))

cd Step_1
if [ ! -f "OUTCAR" ]; then
	run_vasp_stable
fi

cd ../Step_2

cp ../Step_1/WAVECAR .

if [ ! -f "OUTCAR" ]; then
	run_vasp_stable
fi

cd ..

if [ -d "Step_3" ]; then
	# inclusion of local field effects requested

	cd Step_3
	cp ../Step_2/WAVE* . # WAVECAR and WAVEDER

	if [ ! -f "OUTCAR" ]; then
		run_vasp_stable
	fi
	
	cd ..
fi
