#!/bin/bash

# run in directory containing input files for a VASP run

first_energy=$1
final_energy=$2
energy_step=$3

ncores=$((`nproc --all`/2))

if [ ! -f energy_ENCUT.txt ]; then
        echo "Cutoff Energy [eV]; Total calculated energy [eV]; Time [s]" > energy_ENCUT.txt
fi

for cutoff in `seq $first_energy $energy_step $final_energy`; do

	mkdir ENCUT_${cutoff}
	
	cp PO*CAR ENCUT_${cutoff}
	cp KPOINTS ENCUT_${cutoff}

	sed "s/XYZ/${cutoff}/g" INCAR > ENCUT_${cutoff}/INCAR

	cd ENCUT_${cutoff}/

	run_vasp_stable

        # distinguish between Bloechl smearing (-5) and other methods
        if [ `awk '{FS = "="} /ISMEAR/ {print $2}' INCAR` == "-5" ]; then
                # Bloechl smearing - some extra lines are printed (Bloechl correction)
                energy=`grep "energy" OUTCAR | tail -3 | head -1 | awk '{print $NF}'`
        else
                energy=`grep "energy" OUTCAR | tail -1 | awk '{print $NF}'`
        fi

        time=`grep "Elapsed time" OUTCAR | awk 'BEGIN {FS=":"}; {print $2}'`

	cd ..

	echo $cutoff $energy $time >> energy_ENCUT.txt

done
