#!/bin/bash

ncores=`nproc --all`

cd Step_1
if [ ! -f "OUTCAR" ]; then
	if [ `awk '{FS = "="} /LSORBIT/ {print $2}' INCAR` == ".TRUE." ]; then
		mpirun -np $ncores vasp_ncl
	else
		mpirun -np $ncores vasp_std 
	fi

	run_successful=`grep "General" OUTCAR` # when VASP completes a job successfully, it prints some "General timing and accounting informations for this job" at the very end of OUTCAR. Thus, if the job terminates prematurely, run_successful will be empty

	while [ `python -c "print int(not '$run_successful')"` -eq 1 ]; do
		# not '$run_successful' is true, that is, the run was not successful ($run_successful is empty)
		delete_vasp_output

		if [ `awk '{FS = "="} /LSORBIT/ {print $2}' INCAR` == ".TRUE." ]; then
			mpirun -np $ncores vasp_ncl
		else
			mpirun -np $ncores vasp_std
		fi

		run_successful=`grep "General" OUTCAR`
	done
	# when this loop is left, we had a successful run
fi

cd ../Step_2

cp ../Step_1/WAVECAR .

if [ ! -f "OUTCAR" ]; then
        if [ `awk '{FS = "="} /LSORBIT/ {print $2}' INCAR` == ".TRUE." ]; then
                mpirun -np $ncores vasp_ncl
        else
                mpirun -np $ncores vasp_std
        fi

        run_successful=`grep "General" OUTCAR` # when VASP completes a job successfully, it prints some "General timing and accounting informations for this job" at the very end of OUTCAR. Thus, if the job terminates prematurely, run_successful will be empty

        while [ `python -c "print int(not '$run_successful')"` -eq 1 ]; do
                # not '$run_successful' is true, that is, the run was not successful ($run_successful is empty)
                delete_vasp_output

                if [ `awk '{FS = "="} /LSORBIT/ {print $2}' INCAR` == ".TRUE." ]; then
                        mpirun -np $ncores vasp_ncl
                else
                        mpirun -np $ncores vasp_std
                fi

                run_successful=`grep "General" OUTCAR`
        done
        # when this loop is left, we had a successful run
fi

cd ..

if [ -d "Step_3" ]; then
	# inclusion of local field effects requested

	cd Step_3
	cp ../Step_2/WAVE* . # WAVECAR and WAVEDER

	if [ ! -f "OUTCAR" ]; then
		if [ `awk '{FS = "="} /LSORBIT/ {print $2}' INCAR` == ".TRUE." ]; then
			mpirun -np $ncores vasp_ncl
		else
			mpirun -np $ncores vasp_std
		fi

		run_successful=`grep "General" OUTCAR` # when VASP completes a job successfully, it prints some "General timing and accounting informations for this job" at the very end of OUTCAR. Thus, if the job terminates prematurely, run_successful will be empty

		while [ `python -c "print int(not '$run_successful')"` -eq 1 ]; do
			# not '$run_successful' is true, that is, the run was not successful ($run_successful is empty)
			delete_vasp_output

			if [ `awk '{FS = "="} /LSORBIT/ {print $2}' INCAR` == ".TRUE." ]; then
				mpirun -np $ncores vasp_ncl
			else
				mpirun -np $ncores vasp_std
			fi

			run_successful=`grep "General" OUTCAR`
		done
		# when this loop is left, we had a successful run
	fi
	
	cd ..
fi
